#! /bin/sh
python ./post_processing/tags_to_sentences_src.py -i "data/train.xml" -o "data/src_train.xml"
python ./post_processing/tags_to_sentences.py -i "data/train.xml" -o "data/tgt_train.xml"
python ./post_processing/tags_to_sentences_src.py -i "data/dev.xml" -o "data/src_dev.xml"
python ./post_processing/tags_to_sentences.py -i "data/dev.xml" -o "data/tgt_dev.xml"
python ./post_processing/tags_to_sentences_src.py -i "data/testwithedit.xml" -o "data/src_testwithedit.xml"
python ./post_processing/tags_to_sentences.py -i "data/testwithedit.xml" -o "data/tgt_testwithedit.xml"
sed -n 's:.*<sentence.*>\(.*\)</sentence>.*:\1:p' data/src_train.xml > data/src_train.txt
sed -n 's:.*<sentence.*>\(.*\)</sentence>.*:\1:p' data/tgt_train.xml > data/tgt_train.txt
sed -n 's:.*<sentence.*>\(.*\)</sentence>.*:\1:p' data/src_dev.xml > data/src_dev.txt
sed -n 's:.*<sentence.*>\(.*\)</sentence>.*:\1:p' data/tgt_dev.xml > data/tgt_dev.txt
sed -n 's:.*<sentence.*>\(.*\)</sentence>.*:\1:p' data/src_testwithedit.xml > data/src_testwithedit.txt
sed -n 's:.*<sentence.*>\(.*\)</sentence>.*:\1:p' data/tgt_testwithedit.xml > data/tgt_testwithedit.txt
th tools/tokenize.lua <data/src_train.txt> data/src_train.tok
th tools/tokenize.lua <data/tgt_train.txt> data/tgt_train.tok
th tools/tokenize.lua <data/src_dev.txt> data/src_dev.tok
th tools/tokenize.lua <data/tgt_dev.txt> data/tgt_dev.tok
th tools/tokenize.lua <data/src_testwithedit.txt> data/src_testwithedit.tok
th tools/tokenize.lua <data/tgt_testwithedit.txt> data/tgt_testwithedit.tok
rm data/src*.xml data/tgt*.xml data/*.txt
